// <auto-generated />
namespace _24HourGroupAssignment.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewMigrationAfterMerge : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewMigrationAfterMerge));
        
        string IMigrationMetadata.Id
        {
            get { return "202102061850020_NewMigrationAfterMerge"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
